

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DBEntities : DbContext
{
    public DBEntities()
        : base("name=DBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Account> Accounts { get; set; }

    public DbSet<AccountCategory> AccountCategories { get; set; }

    public DbSet<Article> Articles { get; set; }

    public DbSet<ArticleCategory> ArticleCategories { get; set; }

    public DbSet<ArticleMainCategory> ArticleMainCategories { get; set; }

    public DbSet<Client> Clients { get; set; }

    public DbSet<ClientCategory> ClientCategories { get; set; }

    public DbSet<CommentProduct> CommentProducts { get; set; }

    public DbSet<Contact> Contacts { get; set; }

    public DbSet<ContactCategory> ContactCategories { get; set; }

    public DbSet<Order> Orders { get; set; }

    public DbSet<OrderDetailList> OrderDetailLists { get; set; }

    public DbSet<Picture> Pictures { get; set; }

    public DbSet<PictureCategory> PictureCategories { get; set; }

    public DbSet<PictureMainCategory> PictureMainCategories { get; set; }

    public DbSet<Product> Products { get; set; }

    public DbSet<ProductCategory> ProductCategories { get; set; }

    public DbSet<ProductMainCategory> ProductMainCategories { get; set; }

    public DbSet<ProductWisList> ProductWisLists { get; set; }

    public DbSet<Staff> Staffs { get; set; }

    public DbSet<StaffCategory> StaffCategories { get; set; }

    public DbSet<StaffMainCategory> StaffMainCategories { get; set; }

}

