

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class Account
{

    public Account()
    {

        this.Pictures = new HashSet<Picture>();

        this.PictureCategories = new HashSet<PictureCategory>();

        this.PictureMainCategories = new HashSet<PictureMainCategory>();

        this.Articles = new HashSet<Article>();

        this.ArticleCategories = new HashSet<ArticleCategory>();

        this.ArticleMainCategories = new HashSet<ArticleMainCategory>();

        this.Clients = new HashSet<Client>();

        this.ClientCategories = new HashSet<ClientCategory>();

        this.Contacts = new HashSet<Contact>();

        this.ContactCategories = new HashSet<ContactCategory>();

        this.Products = new HashSet<Product>();

        this.ProductCategories = new HashSet<ProductCategory>();

        this.ProductMainCategories = new HashSet<ProductMainCategory>();

        this.Staffs = new HashSet<Staff>();

        this.StaffCategories = new HashSet<StaffCategory>();

        this.StaffMainCategories = new HashSet<StaffMainCategory>();

    }


    public string Username { get; set; }

    public string Password { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Mobi { get; set; }

    public string Address { get; set; }

    public Nullable<bool> Gender { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string AccountCategoryID { get; set; }



    public virtual ICollection<Picture> Pictures { get; set; }

    public virtual ICollection<PictureCategory> PictureCategories { get; set; }

    public virtual ICollection<PictureMainCategory> PictureMainCategories { get; set; }

    public virtual AccountCategory AccountCategory { get; set; }

    public virtual ICollection<Article> Articles { get; set; }

    public virtual ICollection<ArticleCategory> ArticleCategories { get; set; }

    public virtual ICollection<ArticleMainCategory> ArticleMainCategories { get; set; }

    public virtual ICollection<Client> Clients { get; set; }

    public virtual ICollection<ClientCategory> ClientCategories { get; set; }

    public virtual ICollection<Contact> Contacts { get; set; }

    public virtual ICollection<ContactCategory> ContactCategories { get; set; }

    public virtual ICollection<Product> Products { get; set; }

    public virtual ICollection<ProductCategory> ProductCategories { get; set; }

    public virtual ICollection<ProductMainCategory> ProductMainCategories { get; set; }

    public virtual ICollection<Staff> Staffs { get; set; }

    public virtual ICollection<StaffCategory> StaffCategories { get; set; }

    public virtual ICollection<StaffMainCategory> StaffMainCategories { get; set; }

}


public partial class AccountCategory
{

    public AccountCategory()
    {

        this.Accounts = new HashSet<Account>();

    }


    public string AccountCategoryID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }



    public virtual ICollection<Account> Accounts { get; set; }

}


public partial class Article
{

    public int ArticleID { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public string Content { get; set; }

    public string Keyword { get; set; }

    public string ImageList { get; set; }

    public string SourcePage { get; set; }

    public string SourceLink { get; set; }

    public string AttachmentFile { get; set; }

    public Nullable<int> ViewTime { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<int> ArticleCategoryID { get; set; }

    public string CreateBy { get; set; }



    public virtual Account Account { get; set; }

    public virtual ArticleCategory ArticleCategory { get; set; }

}


public partial class ArticleCategory
{

    public ArticleCategory()
    {

        this.Articles = new HashSet<Article>();

    }


    public int ArticleCategoryID { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<int> ArticleMainCategoryID { get; set; }

    public string CreateBy { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<Article> Articles { get; set; }

    public virtual ArticleMainCategory ArticleMainCategory { get; set; }

}


public partial class ArticleMainCategory
{

    public ArticleMainCategory()
    {

        this.ArticleCategories = new HashSet<ArticleCategory>();

    }


    public int ArticleMainCategoryID { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string CreateBy { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<ArticleCategory> ArticleCategories { get; set; }

}


public partial class Client
{

    public Client()
    {

        this.CommentProducts = new HashSet<CommentProduct>();

        this.ProductWisLists = new HashSet<ProductWisList>();

        this.Orders = new HashSet<Order>();

    }


    public int ClientID { get; set; }

    public string Code { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public string Mobi { get; set; }

    public string Address { get; set; }

    public Nullable<bool> Gender { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string ApproveBy { get; set; }

    public Nullable<int> ClientCategoryID { get; set; }

    public string FacebookID { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<CommentProduct> CommentProducts { get; set; }

    public virtual ICollection<ProductWisList> ProductWisLists { get; set; }

    public virtual ClientCategory ClientCategory { get; set; }

    public virtual ICollection<Order> Orders { get; set; }

}


public partial class ClientCategory
{

    public ClientCategory()
    {

        this.Clients = new HashSet<Client>();

    }


    public int ClientCategoryID { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string CreateBy { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<Client> Clients { get; set; }

}


public partial class CommentProduct
{

    public int CommentID { get; set; }

    public int ClientID { get; set; }

    public int ProductID { get; set; }

    public string NameComment { get; set; }

    public string Content { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<bool> Status { get; set; }



    public virtual Client Client { get; set; }

    public virtual Product Product { get; set; }

}


public partial class Contact
{

    public int ContactID { get; set; }

    public string Code { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Mobi { get; set; }

    public string Content { get; set; }

    public string AttachmentFile { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string ApproveBy { get; set; }

    public Nullable<int> ContactCategoryID { get; set; }



    public virtual Account Account { get; set; }

    public virtual ContactCategory ContactCategory { get; set; }

}


public partial class ContactCategory
{

    public ContactCategory()
    {

        this.Contacts = new HashSet<Contact>();

    }


    public int ContactCategoryID { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string CreateBy { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<Contact> Contacts { get; set; }

}


public partial class Order
{

    public Order()
    {

        this.OrderDetailLists = new HashSet<OrderDetailList>();

    }


    public int OrderID { get; set; }

    public string Code { get; set; }

    public Nullable<double> Total { get; set; }

    public string Email { get; set; }

    public string FullName { get; set; }

    public string Mobi { get; set; }

    public string Mobi2 { get; set; }

    public string Address { get; set; }

    public Nullable<bool> Gender { get; set; }

    public Nullable<int> PaymentMethod { get; set; }

    public string Comment { get; set; }

    public Nullable<bool> OrderStatus { get; set; }

    public Nullable<bool> DeliverStatus { get; set; }

    public Nullable<bool> ChargeStatus { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<int> ClientID { get; set; }

    public Nullable<int> StaffID { get; set; }

    public string ImageList { get; set; }

    public Nullable<System.DateTime> DeliverTime { get; set; }



    public virtual Client Client { get; set; }

    public virtual Staff Staff { get; set; }

    public virtual ICollection<OrderDetailList> OrderDetailLists { get; set; }

}


public partial class OrderDetailList
{

    public int OrderID { get; set; }

    public int ProductID { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<double> Price { get; set; }



    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

}


public partial class Picture
{

    public int PictureID { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<int> ViewTime { get; set; }

    public string CreateBy { get; set; }

    public Nullable<int> PictureCategoryID { get; set; }



    public virtual Account Account { get; set; }

    public virtual PictureCategory PictureCategory { get; set; }

}


public partial class PictureCategory
{

    public PictureCategory()
    {

        this.Pictures = new HashSet<Picture>();

    }


    public int PictureCategoryID { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string CreateBy { get; set; }

    public Nullable<int> PictureMainCategoryID { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<Picture> Pictures { get; set; }

    public virtual PictureMainCategory PictureMainCategory { get; set; }

}


public partial class PictureMainCategory
{

    public PictureMainCategory()
    {

        this.PictureCategories = new HashSet<PictureCategory>();

    }


    public int PictureMainCategoryID { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string CreateBy { get; set; }

    public string Icon { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<PictureCategory> PictureCategories { get; set; }

}


public partial class Product
{

    public Product()
    {

        this.CommentProducts = new HashSet<CommentProduct>();

        this.OrderDetailLists = new HashSet<OrderDetailList>();

        this.ProductWisLists = new HashSet<ProductWisList>();

    }


    public int ProductID { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public string Content { get; set; }

    public string Keyword { get; set; }

    public string ImageList { get; set; }

    public string GalleryImageList { get; set; }

    public string SourcePage { get; set; }

    public string SourceLink { get; set; }

    public Nullable<int> ViewTime { get; set; }

    public string AttachmentFile { get; set; }

    public Nullable<double> Price { get; set; }

    public Nullable<double> OldPrice { get; set; }

    public string Promotions { get; set; }

    public string WarrantyPolicy { get; set; }

    public string Specifications { get; set; }

    public string Accessories { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string CreateBy { get; set; }

    public Nullable<int> ProductCategoryID { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<CommentProduct> CommentProducts { get; set; }

    public virtual ICollection<OrderDetailList> OrderDetailLists { get; set; }

    public virtual ICollection<ProductWisList> ProductWisLists { get; set; }

    public virtual ProductCategory ProductCategory { get; set; }

}


public partial class ProductCategory
{

    public ProductCategory()
    {

        this.Products = new HashSet<Product>();

    }


    public int ProductCategoryID { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string CreateBy { get; set; }

    public Nullable<int> ProductMainCategoryID { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<Product> Products { get; set; }

    public virtual ProductMainCategory ProductMainCategory { get; set; }

}


public partial class ProductMainCategory
{

    public ProductMainCategory()
    {

        this.ProductCategories = new HashSet<ProductCategory>();

    }


    public int ProductMainCategoryID { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string CreateBy { get; set; }

    public string Icon { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<ProductCategory> ProductCategories { get; set; }

}


public partial class ProductWisList
{

    public int ID { get; set; }

    public Nullable<int> ClientID { get; set; }

    public Nullable<int> ProductID { get; set; }



    public virtual Client Client { get; set; }

    public virtual Product Product { get; set; }

}


public partial class Staff
{

    public Staff()
    {

        this.Orders = new HashSet<Order>();

    }


    public int StaffID { get; set; }

    public string Code { get; set; }

    public string AcademicTitles { get; set; }

    public string FullName { get; set; }

    public string Specialize { get; set; }

    public string Email { get; set; }

    public string Mobi { get; set; }

    public string Address { get; set; }

    public Nullable<bool> Gender { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public string WorkSchedule { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string CreateBy { get; set; }

    public Nullable<int> StaffCategoryID { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<Order> Orders { get; set; }

    public virtual StaffCategory StaffCategory { get; set; }

}


public partial class StaffCategory
{

    public StaffCategory()
    {

        this.Staffs = new HashSet<Staff>();

    }


    public int StaffCategoryID { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string CreateBy { get; set; }

    public Nullable<int> StaffMainCategoryID { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<Staff> Staffs { get; set; }

    public virtual StaffMainCategory StaffMainCategory { get; set; }

}


public partial class StaffMainCategory
{

    public StaffMainCategory()
    {

        this.StaffCategories = new HashSet<StaffCategory>();

    }


    public int StaffMainCategoryID { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Thumb { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string CreateBy { get; set; }



    public virtual Account Account { get; set; }

    public virtual ICollection<StaffCategory> StaffCategories { get; set; }

}

